### ISSUE TITLE
Is there a reason that userd.conf isn't able to run handlers?

### ISSUE THREAD

**Issue by CaptSpify** [linux-surface/surface-dtx-daemon#9]
`WARN config{file: "/home/captspify/.config/surface-dtx/surface-dtx-userd.conf"}: sdtxu::config: unknown config item, item: handler`

Is that an intentional design decision? or has it just not been implemented?

**Comment by qzed** [comment]
It's a design decision to keep things a bit simpler.

Since the handler essentially decides if the detachment process should be granted or not, doing that per user creates a bit more complexity. You'd then have to collect an ok/not-ok for each connected user-daemon instead (or in addition to the root handler). That then begs the question if a single logged-in user should be able to block al other users (or if there should be some higher-priority users or something like that).

Right now, the user-daemon only handles notifications, which makes it a lot less complex.

Also, I didn't see much benefit of (and much of a use-case for) having per-user handlers. The handler essentially requires root privileges once you want to unmount stuff, unload drivers, or similar things. I see the responsibility of the handler as dealing with hardware stuff, which generally isn't per-user.

Something that I've thought about (but haven't even started implementing yet) is a way of registering "blockers", i.e. a way to allow users and applications to register some reason via the dbus API that essentially says: "Application X of user Y needs access to Z which is connected to the base and thus it cannot be detached". With that, the same problem of a single user blocking something still exists, but now there's more detail associated with that (i.e. a reason why).

Is there anything special that you'd need this for? If you only need a script to run (but not influence the decision wrt. detaching), you could look either into udev rules (although those are again for all users) or write a user-daemon that monitors D-Bus events (see e.g. [here](https://github.com/linux-surface/surface-dtx-daemon/blob/b570ed2f57c65195382df1daed25bb145652af08/surface-dtx-daemon/src/service/event.rs#L26-L37)) and acts on those.

**Comment by CaptSpify** [comment]
OK, that makes sense
I have some user-session specific stuff (xmodmap, xinput, onscreen keyboard launching, etc) that are a little clunky, but not that big of a deal to do via su

Thanks!
